// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBykNWIG6Jw-FxtMFf9ZfiIbjns7qFNFEQ',
    appId: '1:621911305644:web:2b76abae8eb1d353291e09',
    messagingSenderId: '621911305644',
    projectId: 'medicinereminderapp-a77f1',
    authDomain: 'medicinereminderapp-a77f1.firebaseapp.com',
    storageBucket: 'medicinereminderapp-a77f1.appspot.com',
    measurementId: 'G-DQ734KR09J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUDKcncNU9uOYPIgzHJYNFMhqzVMSaeM',
    appId: '1:621911305644:android:b981f405de854fe4291e09',
    messagingSenderId: '621911305644',
    projectId: 'medicinereminderapp-a77f1',
    storageBucket: 'medicinereminderapp-a77f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLbb6SU2gC0iE-idM2kqZkoI9uvWeEMg',
    appId: '1:621911305644:ios:d582d1d6eb14aa17291e09',
    messagingSenderId: '621911305644',
    projectId: 'medicinereminderapp-a77f1',
    storageBucket: 'medicinereminderapp-a77f1.appspot.com',
    iosClientId: '621911305644-3oimdpehlq7l7oh3fl3uageb31ufcpik.apps.googleusercontent.com',
    iosBundleId: 'com.example.dawayee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLbb6SU2gC0iE-idM2kqZkoI9uvWeEMg',
    appId: '1:621911305644:ios:d582d1d6eb14aa17291e09',
    messagingSenderId: '621911305644',
    projectId: 'medicinereminderapp-a77f1',
    storageBucket: 'medicinereminderapp-a77f1.appspot.com',
    iosClientId: '621911305644-3oimdpehlq7l7oh3fl3uageb31ufcpik.apps.googleusercontent.com',
    iosBundleId: 'com.example.dawayee',
  );
}
